// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.
// @dart = 2.12

import 'dart:core';
import 'model/schedule.dart' as prefix2;
import 'model/week_schedule.dart' as prefix1;
import 'package:cloudkit_flutter/parsing/annotations/ck_field_annotation.dart'
    as prefix6;
import 'package:cloudkit_flutter/parsing/annotations/ck_record_name_annotation.dart'
    as prefix5;
import 'package:cloudkit_flutter/parsing/annotations/ck_record_type_annotation.dart'
    as prefix4;
import 'package:cloudkit_flutter/parsing/reflector.dart' as prefix0;
import 'package:cloudkit_flutter/parsing/types/ck_field_type.dart' as prefix3;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'WeekSchedule',
            r'.WeekSchedule',
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 8, 15],
            const <int>[16, 8, 17, 18, 19, 9, 10, 11, 12, 13, 14],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix1.WeekSchedule() : null},
            0,
            0,
            const <int>[],
            const <Object>[
              prefix0.reflector,
              const prefix4.CKRecordTypeAnnotation("WeekSchedule")
            ],
            null),
        r.NonGenericClassMirrorImpl(
            r'Schedule',
            r'.Schedule',
            7,
            1,
            const prefix0.Reflector(),
            const <int>[3, 4, 5, 6, 20, 29],
            const <int>[16, 20, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27, 28],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix2.Schedule() : null},
            1,
            1,
            const <int>[],
            const <Object>[
              prefix0.reflector,
              const prefix4.CKRecordTypeAnnotation("Schedule")
            ],
            null),
        r.GenericClassMirrorImpl(
            r'CKCustomFieldType',
            r'.CKCustomFieldType',
            519,
            2,
            const prefix0.Reflector(),
            const <int>[7, 30, 31, 34],
            const <int>[16, 35, 17, 18, 19, 30, 31, 32, 33],
            const <int>[],
            -1,
            {},
            {},
            {},
            2,
            2,
            const <int>[],
            const <Object>[prefix0.reflector],
            null,
            (o) => false,
            const <int>[3],
            2),
        r.TypeVariableMirrorImpl(r'T', r'.CKCustomFieldType.T',
            const prefix0.Reflector(), -1, 2, <Object>[])
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'uuid',
            32773,
            0,
            const prefix0.Reflector(),
            -1,
            3,
            3,
            const <int>[],
            const <Object>[const prefix5.CKRecordNameAnnotation()]),
        r.VariableMirrorImpl(
            r'startTime',
            32773,
            0,
            const prefix0.Reflector(),
            -1,
            4,
            4,
            const <int>[],
            const <Object>[const prefix6.CKFieldAnnotation("weekStartDate")]),
        r.VariableMirrorImpl(
            r'schedules',
            2129925,
            0,
            const prefix0.Reflector(),
            -1,
            5,
            6,
            const <int>[7],
            const <Object>[const prefix6.CKFieldAnnotation("schedules")]),
        r.VariableMirrorImpl(
            r'uuid',
            32773,
            1,
            const prefix0.Reflector(),
            -1,
            3,
            3,
            const <int>[],
            const <Object>[const prefix5.CKRecordNameAnnotation()]),
        r.VariableMirrorImpl(
            r'code',
            32773,
            1,
            const prefix0.Reflector(),
            -1,
            3,
            3,
            const <int>[],
            const <Object>[const prefix6.CKFieldAnnotation("scheduleCode")]),
        r.VariableMirrorImpl(
            r'blockTimes',
            2129925,
            1,
            const prefix0.Reflector(),
            -1,
            5,
            6,
            const <int>[7],
            const <Object>[const prefix6.CKFieldAnnotation("periodTimes")]),
        r.VariableMirrorImpl(
            r'blockNumbers',
            2129925,
            1,
            const prefix0.Reflector(),
            -1,
            8,
            9,
            const <int>[10],
            const <Object>[const prefix6.CKFieldAnnotation("periodNumbers")]),
        r.VariableMirrorImpl(r'rawValue', 5, 2, const prefix0.Reflector(), -1,
            -1, -1, const <int>[], const []),
        r.MethodMirrorImpl(r'toString', 131074, 0, -1, 7, 7, const <int>[],
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 9),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 10),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 11),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 1, 12),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 13),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 2, 14),
        r.MethodMirrorImpl(r'', 64, 0, -1, 0, 0, const <int>[], const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'==', 131074, -1, -1, 11, 11, const <int>[],
            const <int>[3], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 65538, -1, -1, -1, -1,
            const <int>[], const <int>[4], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 131075, -1, -1, 10, 10, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, -1, -1, 12, 12,
            const <int>[], const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 131074, 1, -1, 7, 7, const <int>[],
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 3, 21),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 3, 22),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 4, 23),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 4, 24),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 5, 25),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 5, 26),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 6, 27),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 6, 28),
        r.MethodMirrorImpl(r'', 64, 1, -1, 1, 1, const <int>[], const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toRecordField', 2, 2, -1, -1, -1, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'getFieldType', 131074, 2, -1, 13, 13,
            const <int>[], const <int>[9], const prefix0.Reflector(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 7, 32),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 7, 33),
        r.MethodMirrorImpl(r'fromRecordField', 0, 2, -1, 14, 2, null,
            const <int>[10], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 131074, -1, -1, 7, 7, const <int>[],
            const <int>[], const prefix0.Reflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'_uuid', 32870, 10, const prefix0.Reflector(),
            -1, 3, 3, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_startTime',
            32870,
            12,
            const prefix0.Reflector(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_schedules',
            2130022,
            14,
            const prefix0.Reflector(),
            -1,
            5,
            6,
            const <int>[7],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(r'other', 32774, 16, const prefix0.Reflector(),
            -1, 15, 15, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            17,
            const prefix0.Reflector(),
            -1,
            16,
            16,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(r'_uuid', 32870, 22, const prefix0.Reflector(),
            -1, 3, 3, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'_code', 32870, 24, const prefix0.Reflector(),
            -1, 3, 3, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'_blockTimes',
            2130022,
            26,
            const prefix0.Reflector(),
            -1,
            5,
            6,
            const <int>[7],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_blockNumbers',
            2130022,
            28,
            const prefix0.Reflector(),
            -1,
            8,
            9,
            const <int>[10],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(r'thisType', 32774, 31, const prefix0.Reflector(),
            -1, 12, 12, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'raw', 6, 34, const prefix0.Reflector(), -1, -1,
            -1, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'_rawValue', 102, 33, const prefix0.Reflector(),
            -1, -1, -1, const <int>[], const [], null, null)
      ],
      <Type>[
        prefix1.WeekSchedule,
        prefix2.Schedule,
        prefix3.CKCustomFieldType,
        String,
        DateTime,
        const m.TypeValue<List<String>>().type,
        List,
        String,
        const m.TypeValue<List<int>>().type,
        List,
        int,
        bool,
        Type,
        prefix3.CKFieldType,
        const r.FakeType(r'.CKCustomFieldType<T>'),
        Object,
        Invocation
      ],
      3,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'uuid': (dynamic instance) => instance.uuid,
        r'startTime': (dynamic instance) => instance.startTime,
        r'schedules': (dynamic instance) => instance.schedules,
        r'code': (dynamic instance) => instance.code,
        r'blockTimes': (dynamic instance) => instance.blockTimes,
        r'blockNumbers': (dynamic instance) => instance.blockNumbers,
        r'toRecordField': (dynamic instance) => instance.toRecordField,
        r'getFieldType': (dynamic instance) => instance.getFieldType,
        r'rawValue': (dynamic instance) => instance.rawValue
      },
      {
        r'uuid=': (dynamic instance, value) => instance.uuid = value,
        r'startTime=': (dynamic instance, value) => instance.startTime = value,
        r'schedules=': (dynamic instance, value) => instance.schedules = value,
        r'code=': (dynamic instance, value) => instance.code = value,
        r'blockTimes=': (dynamic instance, value) =>
            instance.blockTimes = value,
        r'blockNumbers=': (dynamic instance, value) =>
            instance.blockNumbers = value,
        r'rawValue=': (dynamic instance, value) => instance.rawValue = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://0/'),
            const prefix0.Reflector(), const <int>[], {}, {}, const [], null),
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://1/'),
            const prefix0.Reflector(), const <int>[], {}, {}, const [], null),
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://2/'),
            const prefix0.Reflector(), const <int>[], {}, {}, const [], null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
