builders:
  reflectable:
    target: ":reflectable"
    import: "package:cloudkit_flutter/reflectable/reflectable_builder.dart"
    builder_factories: ["reflectableBuilder"]
    build_extensions: {".dart": [".reflectable.dart"]}
    auto_apply: root_package
    build_to: source
    defaults:
      generate_for:
        include:
          - example/lib/main.dart
          - test/*.dart
          - lib/main.dart