name: cloudkit_flutter
description: CloudKit support for Flutter via CloudKit Web Services on Android & iOS
version: 0.1.4
homepage: https://jacksonjude.com
repository: https://github.com/jacksonjude/cloudkit_flutter

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.0.6
  http: ^0.13.5
  reflectable: ^4.0.5
  build_runner: ^2.3.3
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
