name: cloudkit_flutter
description: CloudKit support for Flutter via CloudKit Web Services on Android & iOS
version: 0.2.0
publish_to: none
homepage: https://jacksonjude.com
repository: https://github.com/jacksonjude/cloudkit_flutter

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^3.0.4
  http: ^0.13.5
  reflectable:
    git:
      url: https://github.com/jacksonjude/reflectable.dart.git
      path: reflectable
  build_runner: ^2.2.0
  shared_preferences: ^2.0.15
  sqlbrite: ^2.3.0
  tuple: ^2.0.0
  quiver: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: