name: cloudkit_flutter
description: CloudKit support for Flutter via CloudKit Web Services on Android & iOS
version: 0.1.4
homepage: https://jacksonjude.com
repository: https://github.com/jacksonjude/cloudkit_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^2.0.8
  http: ^0.13.3
  reflectable: ^3.0.2
  build_runner: ^2.0.4
  shared_preferences: ^2.0.6
  idb_sqflite: ^1.0.0
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: